/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAddoneBinop extends PBinop
{
    private TDplus _dplus_;

    public AAddoneBinop()
    {
    }

    public AAddoneBinop(
        TDplus _dplus_)
    {
        setDplus(_dplus_);

    }
    public Object clone()
    {
        return new AAddoneBinop(
            (TDplus) cloneNode(_dplus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddoneBinop(this);
    }

    public TDplus getDplus()
    {
        return _dplus_;
    }

    public void setDplus(TDplus node)
    {
        if(_dplus_ != null)
        {
            _dplus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dplus_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dplus_);
    }

    void removeChild(Node child)
    {
        if(_dplus_ == child)
        {
            _dplus_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dplus_ == oldChild)
        {
            setDplus((TDplus) newChild);
            return;
        }

    }
}
