/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AModuloBinop extends PBinop
{
    private TMode _mode_;

    public AModuloBinop()
    {
    }

    public AModuloBinop(
        TMode _mode_)
    {
        setMode(_mode_);

    }
    public Object clone()
    {
        return new AModuloBinop(
            (TMode) cloneNode(_mode_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuloBinop(this);
    }

    public TMode getMode()
    {
        return _mode_;
    }

    public void setMode(TMode node)
    {
        if(_mode_ != null)
        {
            _mode_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mode_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_mode_);
    }

    void removeChild(Node child)
    {
        if(_mode_ == child)
        {
            _mode_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_mode_ == oldChild)
        {
            setMode((TMode) newChild);
            return;
        }

    }
}
