/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APowBinop extends PBinop
{
    private TDmult _dmult_;

    public APowBinop()
    {
    }

    public APowBinop(
        TDmult _dmult_)
    {
        setDmult(_dmult_);

    }
    public Object clone()
    {
        return new APowBinop(
            (TDmult) cloneNode(_dmult_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPowBinop(this);
    }

    public TDmult getDmult()
    {
        return _dmult_;
    }

    public void setDmult(TDmult node)
    {
        if(_dmult_ != null)
        {
            _dmult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dmult_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dmult_);
    }

    void removeChild(Node child)
    {
        if(_dmult_ == child)
        {
            _dmult_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dmult_ == oldChild)
        {
            setDmult((TDmult) newChild);
            return;
        }

    }
}
