/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDminus extends Token
{
    public TDminus()
    {
        super.setText("--");
    }

    public TDminus(int line, int pos)
    {
        super.setText("--");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDminus(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDminus(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDminus text.");
    }
}
