/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDplus extends Token
{
    public TDplus()
    {
        super.setText("++");
    }

    public TDplus(int line, int pos)
    {
        super.setText("++");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDplus(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDplus(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDplus text.");
    }
}
