/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(3), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(4), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(4), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(5), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(5), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(6), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(7), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(7), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(7), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(7), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(7), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(7), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(7), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(7), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(7), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(7), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(7), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(7), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(7), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(7), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(7), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(7), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(7), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(7), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(7), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(7), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(7), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(7), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(7), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(8), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(9), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(9), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(10), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(10), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(11), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(11), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(12), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(12), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(12), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(12), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(12), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(12), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(12), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(12), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(13), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(13), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(13), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(13), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(13), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(14), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(14), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(14), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(14), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(15), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(15), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(16), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(16), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(17), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(17), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(17), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(17), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(17), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(17), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(17), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(18), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(19), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(19), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(20), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(20), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(21), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(21), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(21), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(21), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(22), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(23), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(23), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(24), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(24), list);
		    }
		    break;


                    case 84:
		    {
			ArrayList list = new84();
			push(goTo(25), list);
		    }
		    break;


                    case 85:
		    {
			ArrayList list = new85();
			push(goTo(26), list);
		    }
		    break;


                    case 86:
		    {
			ArrayList list = new86();
			push(goTo(26), list);
		    }
		    break;


                    case 87:
		    {
			ArrayList list = new87();
			push(goTo(27), list);
		    }
		    break;


                    case 88:
		    {
			ArrayList list = new88();
			push(goTo(27), list);
		    }
		    break;


                    case 89:
		    {
			ArrayList list = new89();
			push(goTo(28), list);
		    }
		    break;


                    case 90:
		    {
			ArrayList list = new90();
			push(goTo(28), list);
		    }
		    break;


                    case 91:
		    {
			ArrayList list = new91();
			push(goTo(29), list);
		    }
		    break;


                    case 92:
		    {
			ArrayList list = new92();
			push(goTo(29), list);
		    }
		    break;


                    case 93:
		    {
			ArrayList list = new93();
			push(goTo(30), list);
		    }
		    break;


                    case 94:
		    {
			ArrayList list = new94();
			push(goTo(30), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PProgramme node1 = (PProgramme) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pprogrammeNode1 = new AProgramme(listNode2);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pprogrammeNode1 = new AProgramme(listNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFuncCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TIdentifier tidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFunction(tidentifierNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PIdentifierValue pidentifiervalueNode1;
        pidentifiervalueNode1 = (PIdentifierValue)nodeArrayList1.get(0);
	if(pidentifiervalueNode1 != null)
	{
	  listNode2.add(pidentifiervalueNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        PIdentifierValue pidentifiervalueNode1;
        TypedLinkedList listNode2 = new TypedLinkedList();
        pidentifiervalueNode1 = (PIdentifierValue)nodeArrayList1.get(0);
        listNode2 = (TypedLinkedList)nodeArrayList2.get(0);
	if(pidentifiervalueNode1 != null)
	{
	  listNode3.add(pidentifiervalueNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PIdentifierValue pidentifiervalueNode1;
        {
        TIdentifier tidentifierNode2;
        Object nullNode3 = null;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pidentifiervalueNode1 = new AIdentifierValue(tidentifierNode2, null);
        }
	nodeList.add(pidentifiervalueNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PIdentifierValue pidentifiervalueNode1;
        {
        TIdentifier tidentifierNode2;
        PValue pvalueNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pvalueNode3 = (PValue)nodeArrayList2.get(0);

        pidentifiervalueNode1 = new AIdentifierValue(tidentifierNode2, pvalueNode3);
        }
	nodeList.add(pidentifiervalueNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        Object nullNode1 = null;
	nodeList.add(nullNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PIdentifierValue pidentifiervalueNode1;
        pidentifiervalueNode1 = (PIdentifierValue)nodeArrayList2.get(0);
	nodeList.add(pidentifiervalueNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        pvalueNode1 = (PValue)nodeArrayList2.get(0);
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        TIdentifier tidentifierNode3;
        PStatement pstatementNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(tidentifierNode2, tidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        TIdentifier tidentifierNode3;
        PStatement pstatementNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(tidentifierNode2, tidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssignStatement(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AMinusAssignStatement(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new ADivAssignStatement(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AAssignListStatement(tidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        Object nullNode3 = null;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        Object nullNode3 = null;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFuncCallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFuncCallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AOrComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AAndComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);

        pcomparisonNode1 = new ANotComparison(pcomparisonNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreatComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALessComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ANeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AEqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new ATrueComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new AFalseComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TPlus tplusNode4;
        tplusNode4 = (TPlus)nodeArrayList2.get(0);

        pbinopNode3 = new APlusBinop(tplusNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArithmeticExpression(pexpressionNode2, pbinopNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TDplus tdplusNode4;
        tdplusNode4 = (TDplus)nodeArrayList2.get(0);

        pbinopNode3 = new AAddoneBinop(tdplusNode4);
        }

        pexpressionNode1 = new AArithmExpression(pexpressionNode2, pbinopNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TMinus tminusNode4;
        tminusNode4 = (TMinus)nodeArrayList2.get(0);

        pbinopNode3 = new AMinusBinop(tminusNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArithmeticExpression(pexpressionNode2, pbinopNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TDminus tdminusNode4;
        tdminusNode4 = (TDminus)nodeArrayList2.get(0);

        pbinopNode3 = new AMinusoneBinop(tdminusNode4);
        }

        pexpressionNode1 = new AArithmExpression(pexpressionNode2, pbinopNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TMult tmultNode4;
        tmultNode4 = (TMult)nodeArrayList2.get(0);

        pbinopNode3 = new AMultBinop(tmultNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArithmeticExpression(pexpressionNode2, pbinopNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TDiv tdivNode4;
        tdivNode4 = (TDiv)nodeArrayList2.get(0);

        pbinopNode3 = new ADivBinop(tdivNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArithmeticExpression(pexpressionNode2, pbinopNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TMode tmodeNode4;
        tmodeNode4 = (TMode)nodeArrayList2.get(0);

        pbinopNode3 = new AModuloBinop(tmodeNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArithmeticExpression(pexpressionNode2, pbinopNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PBinop pbinopNode3;
        PExpression pexpressionNode5;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TDmult tdmultNode4;
        tdmultNode4 = (TDmult)nodeArrayList2.get(0);

        pbinopNode3 = new APowBinop(tdmultNode4);
        }
        pexpressionNode5 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArithmeticExpression(pexpressionNode2, pbinopNode3, pexpressionNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        PExpression pexpressionNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ASubscriptionExpression(tidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ALenExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMaxExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMinExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncCallExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AListDefExpression(pexpressionNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AListDefExpression(pexpressionNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        pvalueNode1 = (PValue)nodeArrayList2.get(0);
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentifierExpression(tidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TIdentifier tidentifierNode2;
        PFunctionCall pfunctioncallNode3;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        pfunctioncallNode3 = (PFunctionCall)nodeArrayList3.get(0);

        pvalueNode1 = new AMethodValue(tidentifierNode2, pfunctioncallNode3);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        pvalueNode1 = (PValue)nodeArrayList1.get(0);
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringliteralNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNone tnoneNode2;
        tnoneNode2 = (TNone)nodeArrayList1.get(0);

        pvalueNode1 = new ANoneValue(tnoneNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TIntegerLiteral tintegerliteralNode2;
        tintegerliteralNode2 = (TIntegerLiteral)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(tintegerliteralNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TIdentifier tidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        {
        }

        pfunctioncallNode1 = new AFunctionCall(tidentifierNode2, listNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TIdentifier tidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pfunctioncallNode1 = new AFunctionCall(tidentifierNode2, listNode4);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        TypedLinkedList listNode2 = new TypedLinkedList();
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
        listNode2 = (TypedLinkedList)nodeArrayList2.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode3.add(pexpressionNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new84()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new85()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new86()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new87()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PIdentifierValue pidentifiervalueNode1;
        pidentifiervalueNode1 = (PIdentifierValue)nodeArrayList1.get(0);
	if(pidentifiervalueNode1 != null)
	{
	  listNode2.add(pidentifiervalueNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new88()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PIdentifierValue pidentifiervalueNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pidentifiervalueNode2 = (PIdentifierValue)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pidentifiervalueNode2 != null)
	{
	  listNode3.add(pidentifiervalueNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new89()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new90()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new91()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new92()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PExpression pexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexpressionNode2 != null)
	{
	  listNode3.add(pexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new93()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PValue pvalueNode1;
        pvalueNode1 = (PValue)nodeArrayList1.get(0);
	if(pvalueNode1 != null)
	{
	  listNode2.add(pvalueNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new94()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PValue pvalueNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pvalueNode2 != null)
	{
	  listNode3.add(pvalueNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {27, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 89}, },
			{{-1, ERROR, 2}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {40, SHIFT, 25}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 3}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {40, SHIFT, 25}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 4}, {44, SHIFT, 45}, },
			{{-1, ERROR, 5}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 6}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 7}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 8}, {44, SHIFT, 49}, },
			{{-1, ERROR, 9}, {1, SHIFT, 50}, {2, SHIFT, 51}, {3, SHIFT, 52}, {4, SHIFT, 53}, {6, SHIFT, 54}, },
			{{-1, ERROR, 10}, {46, ACCEPT, -1}, },
			{{-1, REDUCE, 85}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {27, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 16}, {0, SHIFT, 56}, {18, SHIFT, 57}, {20, SHIFT, 58}, {21, SHIFT, 59}, {22, SHIFT, 60}, {23, SHIFT, 61}, {26, SHIFT, 62}, {44, SHIFT, 63}, },
			{{-1, ERROR, 17}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 18}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 19}, {4, SHIFT, 67}, },
			{{-1, ERROR, 20}, {4, SHIFT, 68}, },
			{{-1, REDUCE, 78}, },
			{{-1, ERROR, 22}, {4, SHIFT, 69}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 25}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 79}, },
			{{-1, REDUCE, 74}, {4, SHIFT, 53}, {6, SHIFT, 71}, {9, SHIFT, 72}, },
			{{-1, REDUCE, 77}, },
			{{-1, ERROR, 29}, {41, SHIFT, 73}, },
			{{-1, REDUCE, 35}, {39, SHIFT, 74}, },
			{{-1, REDUCE, 37}, {38, SHIFT, 75}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 34}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, {30, SHIFT, 80}, {31, SHIFT, 81}, {32, SHIFT, 82}, {33, SHIFT, 83}, {34, SHIFT, 84}, {35, SHIFT, 85}, },
			{{-1, REDUCE, 54}, {14, SHIFT, 86}, {15, SHIFT, 87}, {16, SHIFT, 88}, },
			{{-1, REDUCE, 58}, {17, SHIFT, 89}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 72}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 44}, {41, SHIFT, 90}, },
			{{-1, ERROR, 45}, {19, SHIFT, 91}, },
			{{-1, REDUCE, 20}, {8, SHIFT, 92}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 18}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 29}, {8, SHIFT, 92}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 49}, {4, SHIFT, 96}, },
			{{-1, ERROR, 50}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 51}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 52}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 53}, {4, SHIFT, 17}, {5, SHIFT, 100}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 54}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 86}, },
			{{-1, REDUCE, 90}, },
			{{-1, ERROR, 57}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {40, SHIFT, 25}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 58}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {40, SHIFT, 25}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 59}, {44, SHIFT, 106}, },
			{{-1, ERROR, 60}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 61}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 62}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 63}, {1, SHIFT, 110}, {4, SHIFT, 53}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 65}, {5, SHIFT, 111}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 66}, {7, SHIFT, 112}, {8, SHIFT, 92}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 67}, {28, SHIFT, 21}, {43, SHIFT, 26}, {44, SHIFT, 114}, {45, SHIFT, 28}, },
			{{-1, ERROR, 68}, {28, SHIFT, 21}, {43, SHIFT, 26}, {44, SHIFT, 114}, {45, SHIFT, 28}, },
			{{-1, ERROR, 69}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 71}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 72}, {44, SHIFT, 119}, },
			{{-1, ERROR, 73}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, ERROR, 74}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {40, SHIFT, 25}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 75}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {36, SHIFT, 23}, {37, SHIFT, 24}, {40, SHIFT, 25}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 76}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 79}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 80}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 81}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 82}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 83}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 84}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 85}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 86}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 87}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 88}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 89}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, ERROR, 90}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, ERROR, 91}, {44, SHIFT, 137}, },
			{{-1, ERROR, 92}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 91}, },
			{{-1, REDUCE, 22}, {8, SHIFT, 92}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 96}, {44, SHIFT, 140}, },
			{{-1, REDUCE, 24}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 26}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 27}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 80}, },
			{{-1, REDUCE, 82}, {8, SHIFT, 92}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 102}, {5, SHIFT, 144}, },
			{{-1, ERROR, 103}, {7, SHIFT, 145}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 104}, {41, SHIFT, 146}, },
			{{-1, ERROR, 105}, {41, SHIFT, 147}, },
			{{-1, ERROR, 106}, {19, SHIFT, 148}, },
			{{-1, REDUCE, 21}, {8, SHIFT, 92}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 19}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 30}, {8, SHIFT, 92}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 110}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 113}, {7, SHIFT, 152}, {8, SHIFT, 92}, },
			{{-1, ERROR, 114}, {9, SHIFT, 72}, },
			{{-1, ERROR, 115}, {8, SHIFT, 153}, },
			{{-1, ERROR, 116}, {8, SHIFT, 153}, },
			{{-1, ERROR, 117}, {5, SHIFT, 157}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 118}, {7, SHIFT, 158}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 119}, {4, SHIFT, 53}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 36}, {38, SHIFT, 75}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 50}, {14, SHIFT, 86}, {15, SHIFT, 87}, {16, SHIFT, 88}, },
			{{-1, REDUCE, 52}, {14, SHIFT, 86}, {15, SHIFT, 87}, {16, SHIFT, 88}, },
			{{-1, REDUCE, 45}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 43}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 44}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 42}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 46}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 47}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 55}, {17, SHIFT, 89}, },
			{{-1, REDUCE, 56}, {17, SHIFT, 89}, },
			{{-1, REDUCE, 57}, {17, SHIFT, 89}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 137}, {41, SHIFT, 159}, },
			{{-1, REDUCE, 84}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 92}, },
			{{-1, REDUCE, 7}, {1, SHIFT, 160}, },
			{{-1, ERROR, 141}, {5, SHIFT, 162}, },
			{{-1, REDUCE, 5}, {8, SHIFT, 163}, },
			{{-1, REDUCE, 83}, {8, SHIFT, 92}, },
			{{-1, REDUCE, 81}, },
			{{-1, ERROR, 145}, {1, SHIFT, 166}, },
			{{-1, ERROR, 146}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, ERROR, 147}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, ERROR, 148}, {44, SHIFT, 169}, },
			{{-1, REDUCE, 23}, {8, SHIFT, 92}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 25}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, REDUCE, 69}, },
			{{-1, ERROR, 153}, {28, SHIFT, 21}, {43, SHIFT, 26}, {44, SHIFT, 114}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 93}, },
			{{-1, ERROR, 155}, {5, SHIFT, 171}, {8, SHIFT, 153}, },
			{{-1, ERROR, 156}, {5, SHIFT, 173}, {8, SHIFT, 153}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 61}, },
			{{-1, ERROR, 159}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, ERROR, 160}, {28, SHIFT, 21}, {43, SHIFT, 26}, {44, SHIFT, 114}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 162}, {41, SHIFT, 176}, },
			{{-1, REDUCE, 9}, {44, SHIFT, 140}, },
			{{-1, REDUCE, 87}, },
			{{-1, REDUCE, 6}, {8, SHIFT, 163}, },
			{{-1, ERROR, 166}, {4, SHIFT, 17}, {6, SHIFT, 18}, {24, SHIFT, 19}, {25, SHIFT, 20}, {28, SHIFT, 21}, {29, SHIFT, 22}, {43, SHIFT, 26}, {44, SHIFT, 27}, {45, SHIFT, 28}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 169}, {41, SHIFT, 180}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 94}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 176}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 88}, },
			{{-1, REDUCE, 28}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {13, SHIFT, 79}, },
			{{-1, ERROR, 180}, {0, SHIFT, 1}, {18, SHIFT, 2}, {20, SHIFT, 3}, {21, SHIFT, 4}, {22, SHIFT, 5}, {23, SHIFT, 6}, {26, SHIFT, 7}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 17}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, {15, 55}, },
			{{-1, 12}, },
			{{-1, 141}, },
			{{-1, 142}, {163, 177}, },
			{{-1, 164}, {165, 178}, },
			{{-1, 161}, },
			{{-1, 13}, {73, 121}, {90, 136}, {146, 167}, {147, 168}, {159, 174}, {176, 181}, {180, 182}, },
			{{-1, 29}, {3, 44}, {57, 104}, {58, 105}, },
			{{-1, 30}, },
			{{-1, 31}, {74, 122}, },
			{{-1, 32}, {75, 123}, },
			{{-1, 33}, {25, 70}, },
			{{-1, 34}, {5, 46}, {6, 47}, {7, 48}, {17, 65}, {18, 66}, {50, 97}, {51, 98}, {52, 99}, {53, 101}, {54, 103}, {60, 107}, {61, 108}, {62, 109}, {69, 117}, {71, 118}, {80, 126}, {81, 127}, {82, 128}, {83, 129}, {84, 130}, {85, 131}, {92, 138}, {110, 151}, {166, 179}, },
			{{-1, 35}, {76, 124}, {79, 125}, },
			{{-1, 36}, {86, 132}, {87, 133}, {88, 134}, },
			{{-1, 37}, {89, 135}, },
			{{-1, 38}, },
			{{-1, 154}, {155, 172}, {156, 172}, },
			{{-1, 39}, },
			{{-1, 40}, },
			{{-1, 41}, {67, 115}, {68, 116}, {153, 170}, {160, 175}, },
			{{-1, 42}, },
			{{-1, 43}, {0, 14}, {15, 14}, {16, 64}, {72, 120}, {73, 14}, {90, 14}, {146, 14}, {147, 14}, {159, 14}, {176, 14}, {180, 14}, },
			{{-1, 102}, },
			{{-1, 93}, {48, 95}, {94, 139}, {109, 150}, {113, 139}, {143, 139}, {149, 139}, },
			{{-1, 15}, },
			{{-1, 165}, },
			{{-1, 16}, },
			{{-1, 94}, {66, 113}, {101, 143}, {107, 149}, },
			{{-1, 155}, {116, 156}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'if', 'while', 'for', 'print', 'return', 'assert', 'def', identifier, EOF",
			"expecting: tab, 'if', 'while', 'for', 'print', 'return', 'assert', identifier",
			"expecting: '(', '[', 'max', 'min', 'None', 'len', 'true', 'false', 'not', integer literal, identifier, string literal",
			"expecting: identifier",
			"expecting: '(', '[', 'max', 'min', 'None', 'len', integer literal, identifier, string literal",
			"expecting: '=', '-=', '/=', '(', '['",
			"expecting: EOF",
			"expecting: '('",
			"expecting: tab, ')', ']', ',', '+', '++', '--', '-', '*', '/', '%', '**', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', '<=', '<', '>=', '>', '!=', '==', 'and', 'or', ':', identifier, EOF",
			"expecting: 'and', 'or', ':'",
			"expecting: '(', '[', 'max', 'min', 'None', 'len', 'true', 'false', integer literal, identifier, string literal",
			"expecting: tab, '(', ')', '[', ']', ',', '.', '+', '++', '--', '-', '*', '/', '%', '**', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', '<=', '<', '>=', '>', '!=', '==', 'and', 'or', ':', identifier, EOF",
			"expecting: ':'",
			"expecting: 'or', ':'",
			"expecting: '+', '++', '--', '-', '<=', '<', '>=', '>', '!=', '=='",
			"expecting: tab, ')', ']', ',', '+', '++', '--', '-', '*', '/', '%', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', '<=', '<', '>=', '>', '!=', '==', 'and', 'or', ':', identifier, EOF",
			"expecting: 'in'",
			"expecting: tab, ',', '+', '++', '--', '-', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', identifier, EOF",
			"expecting: tab, '+', '++', '--', '-', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', identifier, EOF",
			"expecting: '(', ')', '[', 'max', 'min', 'None', 'len', integer literal, identifier, string literal",
			"expecting: '=', '('",
			"expecting: ')', '+', '++', '--', '-'",
			"expecting: ']', ',', '+', '++', '--', '-'",
			"expecting: 'None', integer literal, identifier, string literal",
			"expecting: tab, ')', ']', ',', '+', '++', '--', '-', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', '<=', '<', '>=', '>', '!=', '==', 'and', 'or', ':', identifier, EOF",
			"expecting: tab, ')', ']', ',', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', identifier, EOF",
			"expecting: tab, ',', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', identifier, EOF",
			"expecting: ')', ',', '+', '++', '--', '-'",
			"expecting: ')'",
			"expecting: ']', '+', '++', '--', '-'",
			"expecting: ']', ','",
			"expecting: '.'",
			"expecting: ','",
			"expecting: '+', '++', '--', '-', 'and', 'or', ':'",
			"expecting: tab, ')', ']', ',', '+', '++', '--', '-', 'if', 'while', 'for', 'print', 'return', 'assert', 'def', identifier, EOF",
			"expecting: '=', ')', ','",
			"expecting: ')', ','",
			"expecting: '='",
			"expecting: ')', ',', identifier",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 2, 3, 4, 4, 4, 3, 5, 6, 0, 0, 0, 0, 0, 1, 4, 4, 7, 7, 8, 7, 9, 9, 10, 8, 11, 8, 12, 13, 9, 9, 9, 14, 15, 8, 8, 8, 8, 8, 8, 8, 8, 12, 16, 17, 18, 17, 7, 4, 4, 4, 19, 4, 0, 1, 2, 2, 3, 4, 4, 4, 20, 0, 21, 22, 23, 23, 4, 9, 4, 3, 1, 2, 2, 4, 24, 24, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 4, 25, 26, 0, 3, 18, 18, 18, 8, 27, 28, 29, 12, 12, 16, 17, 18, 17, 4, 8, 8, 30, 31, 32, 32, 21, 29, 7, 8, 0, 9, 9, 15, 15, 33, 33, 33, 33, 33, 33, 8, 8, 8, 8, 0, 12, 34, 25, 35, 28, 36, 36, 8, 37, 1, 1, 3, 26, 0, 18, 8, 23, 36, 36, 36, 8, 8, 1, 23, 36, 12, 38, 36, 36, 4, 0, 0, 12, 36, 8, 36, 8, 0, 36, 1, 36, 36, 18, 1, 0, 0, 
        };*/
}
